kind: Service
apiVersion: v1
metadata:
  name: orko-service
spec:
  ports:
  - name: service-one
    protocol: TCP
    port: 4444
    targetPort: 80
  selector:
    app: ex-orko
  type: LoadBalancer

---

kind: Service
apiVersion: v1
metadata:
  name: skeletor-service
spec:
  ports:
  - name: service-one
    protocol: TCP
    port: 4444
    targetPort: 8080
  selector:
    app: ex-skeletor
  type: LoadBalancer